CREATE DATABASE IF NOT EXISTS globalsystemllc;

CREATE TABLE IF NOT EXISTS roles(
    id INT AUTO_INCREMENT PRIMARY KEY,
    roll VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO roles(roll) 
VALUES ('administrador'),
('vendedor');

CREATE TABLE IF NOT EXISTS usuarios(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    roll VARCHAR(50) NOT NULL,
    correo VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL DEFAULT '123456',
    FOREIGN KEY (roll) REFERENCES roles (roll)
);
INSERT INTO usuarios(nombre, roll, correo) 
VALUES('Administrador', 'administrador', 'administrador@gmail.com');

CREATE TABLE IF NOT EXISTS calzados(
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    color VARCHAR(50),
    precio DECIMAL
);

CREATE TABLE IF NOT EXISTS tallas(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_calzado INT NOT NULL UNIQUE,
    n1 INT NOT NULL DEFAULT 0,
    n2 INT NOT NULL DEFAULT 0,
    n3 INT NOT NULL DEFAULT 0,
    n4 INT NOT NULL DEFAULT 0,
    n5 INT NOT NULL DEFAULT 0,
    n6 INT NOT NULL DEFAULT 0,
    n7 INT NOT NULL DEFAULT 0,
    n8 INT NOT NULL DEFAULT 0,
    n9 INT NOT NULL DEFAULT 0,
    n10 INT NOT NULL DEFAULT 0,
    n11 INT NOT NULL DEFAULT 0,
    n12 INT NOT NULL DEFAULT 0,
    n13 INT NOT NULL DEFAULT 0,
    n14 INT NOT NULL DEFAULT 0,
    n15 INT NOT NULL DEFAULT 0,
    n16 INT NOT NULL DEFAULT 0,
    n17 INT NOT NULL DEFAULT 0,
    n18 INT NOT NULL DEFAULT 0,
    n19 INT NOT NULL DEFAULT 0,
    n20 INT NOT NULL DEFAULT 0,
    n21 INT NOT NULL DEFAULT 0,
    n22 INT NOT NULL DEFAULT 0,
    n23 INT NOT NULL DEFAULT 0,
    n24 INT NOT NULL DEFAULT 0,
    n25 INT NOT NULL DEFAULT 0,
    n26 INT NOT NULL DEFAULT 0,
    n27 INT NOT NULL DEFAULT 0,
    n28 INT NOT NULL DEFAULT 0,
    n29 INT NOT NULL DEFAULT 0,
    n30 INT NOT NULL DEFAULT 0,
    n31 INT NOT NULL DEFAULT 0,
    n32 INT NOT NULL DEFAULT 0,
    n33 INT NOT NULL DEFAULT 0,
    n34 INT NOT NULL DEFAULT 0,
    n35 INT NOT NULL DEFAULT 0,
    n36 INT NOT NULL DEFAULT 0,
    n37 INT NOT NULL DEFAULT 0,
    n38 INT NOT NULL DEFAULT 0,
    n39 INT NOT NULL DEFAULT 0,
    n40 INT NOT NULL DEFAULT 0,
    n41 INT NOT NULL DEFAULT 0,
    n42 INT NOT NULL DEFAULT 0,
    n43 INT NOT NULL DEFAULT 0,
    n44 INT NOT NULL DEFAULT 0,
    n45 INT NOT NULL DEFAULT 0,
    n46 INT NOT NULL DEFAULT 0,
    n47 INT NOT NULL DEFAULT 0,
    n48 INT NOT NULL DEFAULT 0,
    n49 INT NOT NULL DEFAULT 0,
    n50 INT NOT NULL DEFAULT 0,
    FOREIGN KEY (id_calzado) REFERENCES calzados (id)
);

CREATE TABLE IF NOT EXISTS ventas(
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_vendedor INT NOT NULL,
    id_calzado INT NOT NULL,
    talla INT NOT NULL,
    cantidad INT NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    importe DECIMAL(10,2) NOT NULL,
    cliente VARCHAR(50),
    rif_ci VARCHAR(50),
    direccion VARCHAR(255),
    telefono VARCHAR(50),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_vendedor) REFERENCES usuarios (id),
    FOREIGN KEY (id_calzado) REFERENCES calzados (id)
);